language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-stable

# Unit tests run the normal pillar tests
# Integration tests test that pillar itself can interact with generated files, pdf generation, etc.
# System tests test that we can install and use pillar as a black box
env:
  global:
    - TEXLIVE_RELEASE=2019
    - TEXLIVE_MIRROR=http://mirror.ctan.org/systems/texlive/tlnet
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf

install:
  - git clone https://github.com/pillar-markup/pillar.git -b dev-7
  - ./pillar/scripts/build.sh
  - source pillar/scripts/ci/support.sh && install-texlive
  - source _support/latex/ensure-deps.sh

script:
  - ./pillar/build/pillar build pdf

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - mv _result/pdf/index.pdf Clap-wip.pdf
  - bash upload.sh Clap-wip.pdf

branches:
  except:
    - /^(?i:continuous)$/
